# Notebook de Definición del Problema y Entorno Reproducible — Fase 1 (F1)

**Proyecto:** Caracterización e Inequidad en los Resultados Académicos del SIMCE 4º Básico en Chile  
**Dataset:** Agencia de Calidad de la Educación — SIMCE 2025 por RBD (`simce4b2025_rbd_final.csv`)  
**Asignatura:** Programación para la Ciencia de Datos e Inteligencia Artificial  

---

### Propósito de la Fase 1
Este cuaderno construye y verifica el **andamiaje técnico y metodológico** necesario para garantizar la reproducibilidad completa del proyecto antes de realizar transformaciones de datos en la Fase 2.

**Flujo de ejecución:**  
**Definir → Configurar → Verificar → Estructurar → Documentar → Versionar**

In [1]:
import sys                       # Intérprete en ejecución
import json                      # Exportación de metadatos JSON
import platform                  # Sistema operativo
import subprocess                # Diagnóstico de Git
import shutil                    # Verificación de ejecutables
import importlib                 # Gestión de módulos dinámicos
from pathlib import Path         # Rutas relativas agnósticas al SO
from datetime import date

import numpy as np               # Verificación del entorno científico
import pandas as pd              # Generación de tablas de documentación F1

# Fijar semilla global para reproducibilidad técnica
SEMILLA = 42
np.random.seed(SEMILLA)

print(f"Cuaderno de la Fase 1 iniciado con éxito · {date.today().isoformat()}")

Cuaderno de la Fase 1 iniciado con éxito · 2026-09-14

## 1. Definición del problema, objetivos y alcance

En esta sección se formaliza la problemática del proyecto, las preguntas de investigación,
los objetivos, el alcance, las restricciones y los supuestos que conectan la Fase 1 con
el pipeline de preprocesamiento implementado en la Fase 2.

In [ ]:
PROYECTO = {
    "titulo": (
        "Caracterización e Inequidad en los Resultados Académicos "
        "del SIMCE 4º Básico en Chile"
    ),
    "grupo": "Grupo 7",
    "asignatura": "MCDI500 · Programación para la Ciencia de Datos",
    "integrantes": [
        "Felipe Palma Barrientos",
        "Vicente Aguilar Rojas",
        "Cristian Grandon Grandon",
        "Jorge Gutierrez Jaramillo",
    ],

    "problematica": (
        "Los recursos destinados al apoyo y fortalecimiento educativo son limitados, por lo que resulta "
        "necesario contar con evidencia que permita focalizar de manera eficiente las acciones en aquellos "
        "establecimientos y territorios que presentan mayores brechas de desempeño. En este contexto, los "
        "resultados de la prueba SIMCE constituyen una fuente relevante de información para identificar "
        "diferencias en el rendimiento académico. El presente proyecto busca analizar si existen diferencias "
        "significativas en los puntajes de Matemática obtenidos por los establecimientos educacionales de "
        "Chile según su ubicación geográfica, considerando los resultados de estudiantes de 4° Básico en el "
        "año 2025. A partir de este análisis se pretende identificar territorios que concentren menores niveles "
        "de desempeño y generar evidencia que contribuya a la priorización y focalización de recursos y apoyos "
        "educativos."
    ),

    "objetivo_general": (
        "Desarrollar un flujo reproducible de análisis que permita identificar y evaluar las diferencias "
        "en los puntajes promedio de la prueba SIMCE de Matemática de 4° Básico 2025 entre los "
        "establecimientos educacionales de Chile según su ubicación geográfica, determinando si dichas "
        "diferencias son estadísticamente significativas e identificando establecimientos y territorios "
        "con menores niveles de desempeño que puedan constituir focos prioritarios para el análisis y "
        "la focalización de apoyos educativos."
    ),

    "objetivos_especificos": [
        "Delimitar la pregunta de investigación y definir las variables necesarias para analizar las diferencias territoriales en los resultados SIMCE de Matemática de 4° Básico 2025.",
        "Seleccionar, documentar y validar el conjunto de datos SIMCE 2025, verificando su pertinencia, estructura, calidad e integridad respecto de la problemática planteada.",
        "Configurar un entorno de trabajo reproducible mediante Python, Jupyter Notebooks, gestión de dependencias y control de versiones con Git y GitHub.",
        "Construir un pipeline reproducible para la obtención, limpieza, transformación y validación de los datos, incluyendo el tratamiento de valores faltantes, tipos de datos y variables categóricas.",
    ],

    "preguntas": [
        "¿Existen diferencias estadísticamente significativas en los puntajes promedio de Matemática del SIMCE 2025 de 4° Básico entre los establecimientos educacionales según su ubicación geográfica?",
        "¿Qué regiones, provincias y comunas concentran establecimientos con puntajes promedio de Matemática inferiores al desempeño nacional observado en el SIMCE 2025?",
        "¿Qué establecimientos y territorios pueden identificarse como potenciales focos de priorización para apoyos educativos a partir de sus resultados de Matemática y su ubicación geográfica?"
    ],

    "criterios_exito": [
        "El repositorio puede clonarse en un equipo distinto, configurarse mediante el archivo de dependencias y ejecutar los notebooks F1 y F2 de inicio a fin sin intervención manual ni errores.",
        "El pipeline de preprocesamiento genera un dataset final íntegro y consistente, con tratamiento documentado de valores faltantes, tipos de datos, transformaciones y validaciones de calidad.",
        "Cada decisión relevante de limpieza, transformación o exclusión de datos queda justificada mediante evidencia cuantitativa y documentada en el notebook.",
        "El análisis permite determinar si existen diferencias estadísticamente significativas en los puntajes de Matemática del SIMCE 2025 según la ubicación geográfica de los establecimientos.",
        "Existe trazabilidad completa entre problemática, objetivos, mapa conceptual, notebooks, README, informe técnico y repositorio GitHub, con commits identificables de todos los integrantes."
    ],

    "alcance": {
        "incluye": [
            "Análisis de los resultados de Matemática de la prueba SIMCE 2025 correspondiente a estudiantes de 4° Básico.",
            "Comparación de los puntajes promedio de los establecimientos educacionales según su ubicación geográfica, considerando región, provincia y comuna.",
            "Aplicación de técnicas descriptivas e inferenciales para determinar si las diferencias territoriales observadas son estadísticamente significativas.",
            "Identificación de establecimientos y territorios con niveles de desempeño inferiores al conjunto analizado como potenciales focos de priorización educativa.",
            "Preparación, limpieza, transformación y validación reproducible del conjunto de datos mediante Python y Jupyter Notebooks."
        ],

        "excluye": [
            "Análisis de resultados SIMCE de años anteriores o evaluación de tendencias históricas.",
            "Predicción de puntajes SIMCE futuros o construcción de modelos de pronóstico.",
            "Análisis de otros niveles educativos, cursos o asignaturas distintas de Matemática de 4° Básico.",
            "Determinación de relaciones causales entre la ubicación geográfica y el desempeño académico.",
            "Evaluación directa de la efectividad de políticas públicas, programas educativos o asignación presupuestaria."
        ]
    },

    "restricciones": [
        "El análisis utiliza únicamente información disponible para el año 2025.",
        "Los resultados permiten identificar asociaciones y diferencias territoriales, pero no establecer causalidad.",
        "La capacidad de análisis está condicionada por la disponibilidad y calidad de los datos publicados en el dataset SIMCE."
    ],
}

# Correspondencia explícita entre la formulación de F1 y lo implementado en F2.
PROYECTO["pregunta_f1_f2"] = (
    "¿Cómo preparar una base comparable de establecimientos para estudiar las diferencias "
    "territoriales en el puntaje promedio SIMCE de Matemática de 4° Básico 2025?"
)

PROYECTO["alcance_f1_f2"] = [
    (
        "F1 define la problemática, la unidad de análisis, la fuente, las variables del "
        "dataset bruto, el entorno reproducible y los criterios de calidad."
    ),
    (
        "F2 implementa la carga selectiva de 20 variables, la limpieza, transformación, "
        "clasificación de efectividad, auditoría de exclusiones, cobertura regional y "
        "validación técnica del producto analítico."
    ),
    (
        "F2 genera 6.524 establecimientos Efectivos con 30 variables y conserva los "
        "619 registros No Efectivos en auditoria_filtro.csv; las comparaciones descriptivas, "
        "pruebas de significancia y priorización territorial quedan para fases posteriores."
    ),
]

PROYECTO["supuestos"] = [
    (
        "La unidad de análisis es el establecimiento educacional identificado mediante RBD, "
        "no cada estudiante. Los análisis territoriales posteriores describirán establecimientos."
    ),
    (
        "Los puntajes publicados para Matemática de 4° Básico 2025 se utilizan en su escala "
        "original y corresponden al resultado promedio informado para cada establecimiento."
    ),
    (
        "La ubicación geográfica permite describir y comparar diferencias territoriales, "
        "pero no permite establecer que el territorio sea la causa del desempeño observado."
    ),
    (
        "F2 no imputa puntajes, identidad institucional ni información geográfica. Los registros "
        "que no cumplen la regla operacional de efectividad permanecen documentados mediante "
        "auditoria_filtro.csv."
    ),
    (
        "Las variables porcentuales asociadas a estándares de aprendizaje no forman parte del "
        "producto analítico de F2. Su utilización podrá reconsiderarse en fases posteriores "
        "si los objetivos analíticos lo requieren."
    ),
    (
        "Los registros con marca_mate4b_rbd = 2 que conservan puntaje permanecen clasificados "
        "como No Efectivos y se mantienen explícitamente identificados en la auditoría, "
        "preservando la trazabilidad respecto de la documentación oficial SIMCE 2025."
    ),
]

PROYECTO["criterios_exito_f1_f2"] = [
    (
        "El producto analítico contiene una fila por RBD, con puntaje disponible, alumnos "
        "evaluados mayores que cero e información territorial completa."
    ),
    (
        "El curso y año corresponden a Matemática de 4° Básico 2025, la fecha de la base "
        "se encuentra correctamente convertida y las variables categóricas utilizadas se "
        "verifican mediante catálogos explícitos."
    ),
    (
        "Los 7.143 registros del dataset bruto quedan reconciliados entre establecimientos "
        "Efectivos y No Efectivos, manteniendo las exclusiones trazables mediante "
        "auditoria_filtro.csv."
    ),
    (
        "El efecto territorial del filtro queda documentado mediante cobertura_regional.csv "
        "utilizando conteos de registros y alumnos antes y después del filtrado."
    ),
    (
        "El pipeline genera un dataset procesado reproducible y validado para las fases "
        "posteriores, sin realizar todavía análisis inferencial ni priorización territorial."
    ),
]

In [3]:
# Mostramos los acuerdos para que no queden escondidos en la configuración.
print(PROYECTO["pregunta_f1_f2"])
for apartado in ["alcance_f1_f2", "supuestos", "criterios_exito_f1_f2"]:
    print("\n" + apartado.replace("_", " ").capitalize())
    for acuerdo in PROYECTO[apartado]:
        print("-", acuerdo)

¿Cómo preparar una base comparable de establecimientos para estudiar las diferencias territoriales en el puntaje promedio SIMCE de Matemática de 4° Básico 2025?

Alcance f1 f2
- F1 define la problemática, la unidad de análisis, la fuente, las variables del dataset bruto, el entorno reproducible y los criterios de calidad.
- F2 implementa la carga selectiva de 20 variables, la limpieza, transformación, clasificación de efectividad, auditoría de exclusiones, cobertura regional y validación técnica del producto analítico.
- F2 genera 6.524 establecimientos Efectivos con 30 variables y conserva los 619 registros No Efectivos en auditoria_filtro.csv; las comparaciones descriptivas, pruebas de significancia y priorización territorial quedan para fases posteriores.

Supuestos
- La unidad de análisis es el establecimiento educacional identificado mediante RBD, no cada estudiante. Los análisis territoriales posteriores describirán establecimientos.
- Los puntajes publicados para Matemática de 4° Básico 2025 se utilizan en su escala original y corresponden al resultado promedio informado para cada establecimiento.
- La ubicación geográfica permite describir y comparar diferencias territoriales, pero no permite establecer que el territorio sea la causa del desempeño observado.
- F2 no imputa puntajes, identidad institucional ni información geográfica. Los registros que no cumplen la regla operacional de efectividad permanecen documentados mediante auditoria_filtro.csv.
- Las variables porcentuales asociadas a estándares de aprendizaje no forman parte del producto analítico de F2. Su utilización podrá reconsiderarse en fases posteriores si los objetivos analíticos lo requieren.
- Los registros con marca_mate4b_rbd = 2 que conservan puntaje permanecen clasificados como No Efectivos y se mantienen explícitamente identificados en la auditoría, preservando la trazabilidad respecto de la documentación oficial SIMCE 2025.

Criterios exito f1 f2
- El producto analítico contiene una fila por RBD, con puntaje disponible, alumnos evaluados mayores que cero e información territorial completa.
- El curso y año corresponden a Matemática de 4° Básico 2025, la fecha de la base se encuentra correctamente convertida y las variables categóricas utilizadas se verifican mediante catálogos explícitos.
- Los 7.143 registros del dataset bruto quedan reconciliados entre establecimientos Efectivos y No Efectivos, manteniendo las exclusiones trazables mediante auditoria_filtro.csv.
- El efecto territorial del filtro queda documentado mediante cobertura_regional.csv utilizando conteos de registros y alumnos antes y después del filtrado.
- El pipeline genera un dataset procesado reproducible y validado para las fases posteriores, sin realizar todavía análisis inferencial ni priorización territorial.

In [4]:
def presentar_proyecto(config): # config corresponde la variable proyecto, donde se considerarán todas las claves.
    
    obligatorias = ("titulo", "problematica", "objetivo_general", "objetivos_especificos") # Estos son los parámetros mínimos que se deben considerar para que el proyecto sea presentado.
    faltantes = [c for c in obligatorias if c not in config]
    if faltantes:
        raise KeyError(f"Faltan claves obligatorias en la configuracion: {faltantes}") # Se genera un mensaje de error si falta algún parámetro, indicando cual falta.

    print(config["titulo"].upper())
    print("=" * 60)
    print(f"{config['asignatura']} · {config['grupo']}")
    print("\nProblemática")
    print(config["problematica"])
    print("\nObjetivo general")
    print(config["objetivo_general"])
    print("\nObjetivos específicos")
    for i, obj in enumerate(config["objetivos_especificos"], start=1):
        print(f"  {i}. {obj}")
    print("\nPreguntas que orientan el trabajo")
    for pregunta in config["preguntas"]:
        print(f"  · {pregunta}")


presentar_proyecto(PROYECTO)

CARACTERIZACIÓN E INEQUIDAD EN LOS RESULTADOS ACADÉMICOS DEL SIMCE 4º BÁSICO EN CHILE
============================================================
MCDI500 · Programación para la Ciencia de Datos · Grupo 7

Problemática
Los recursos destinados al apoyo y fortalecimiento educativo son limitados, por lo que resulta necesario contar con evidencia que permita focalizar de manera eficiente las acciones en aquellos establecimientos y territorios que presentan mayores brechas de desempeño. En este contexto, los resultados de la prueba SIMCE constituyen una fuente relevante de información para identificar diferencias en el rendimiento académico. El presente proyecto busca analizar si existen diferencias significativas en los puntajes de Matemática obtenidos por los establecimientos educacionales de Chile según su ubicación geográfica, considerando los resultados de estudiantes de 4° Básico en el año 2025. A partir de este análisis se pretende identificar territorios que concentren menores niveles de desempeño y generar evidencia que contribuya a la priorización y focalización de recursos y apoyos educativos.

Objetivo general
Desarrollar un flujo reproducible de análisis que permita identificar y evaluar las diferencias en los puntajes promedio de la prueba SIMCE de Matemática de 4° Básico 2025 entre los establecimientos educacionales de Chile según su ubicación geográfica, determinando si dichas diferencias son estadísticamente significativas e identificando establecimientos y territorios con menores niveles de desempeño que puedan constituir focos prioritarios para el análisis y la focalización de apoyos educativos.

Objetivos específicos
  1. Delimitar la pregunta de investigación y definir las variables necesarias para analizar las diferencias territoriales en los resultados SIMCE de Matemática de 4° Básico 2025.
  2. Seleccionar, documentar y validar el conjunto de datos SIMCE 2025, verificando su pertinencia, estructura, calidad e integridad respecto de la problemática planteada.
  3. Configurar un entorno de trabajo reproducible mediante Python, Jupyter Notebooks, gestión de dependencias y control de versiones con Git y GitHub.
  4. Construir un pipeline reproducible para la obtención, limpieza, transformación y validación de los datos, incluyendo el tratamiento de valores faltantes, tipos de datos y variables categóricas.
  5. Caracterizar los resultados SIMCE de Matemática mediante técnicas de análisis descriptivo y territorial, considerando distintos niveles geográficos como región, provincia y comuna.
  6. Aplicar técnicas de análisis inferencial que permitan determinar si las diferencias observadas en los puntajes promedio entre territorios son estadísticamente significativas.
  7. Identificar establecimientos y territorios que concentren menores niveles de desempeño, generando evidencia que permita reconocer potenciales focos de priorización para apoyos educativos.
  8. Implementar el procesamiento y análisis mediante funciones modulares, estructuras de control y validaciones que aseguren la consistencia entre los datos de entrada, procesamiento y resultados.
  9. Documentar y comunicar de forma reproducible las decisiones técnicas, procedimientos, resultados y hallazgos mediante Jupyter Notebooks, GitHub, visualizaciones y un informe técnico.

Preguntas que orientan el trabajo
  · ¿Existen diferencias estadísticamente significativas en los puntajes promedio de Matemática del SIMCE 2025 de 4° Básico entre los establecimientos educacionales según su ubicación geográfica?
  · ¿Qué regiones, provincias y comunas concentran establecimientos con puntajes promedio de Matemática inferiores al desempeño nacional observado en el SIMCE 2025?
  · ¿Qué establecimientos y territorios pueden identificarse como potenciales focos de priorización para apoyos educativos a partir de sus resultados de Matemática y su ubicación geográfica?

## 2. Verificación del entorno de trabajo

En esta sección se comprueba que el entorno de ejecución cuente con las herramientas necesarias para desarrollar el proyecto de forma reproducible.

Se verifica:

- La versión de Python utilizada.
- El sistema operativo.
- El intérprete activo.
- La existencia de un entorno virtual.
- La disponibilidad y versión de las principales librerías utilizadas en el proyecto.

Esta verificación permite detectar diferencias entre equipos y facilita que el proyecto pueda ejecutarse nuevamente en otro computador con una configuración equivalente.

In [5]:
#Verificar entorno de ejecución y dependencias
DEPENDENCIAS = ["numpy", "pandas", "matplotlib", "seaborn"]
NOMBRE_EN_PYPI = {"seaborn": "seaborn"}

def verificar_entorno(dependencias):
    """Comprueba intérprete, entorno virtual, directorio de trabajo y versiones."""
    reporte = {}
    ejecutable = Path(sys.executable)
    en_venv = ".venv" in ejecutable.parts or sys.prefix != sys.base_prefix
    
    reporte["interprete"] = str(ejecutable)
    reporte["entorno_virtual"] = bool(en_venv)
    
    print("Intérprete       :", ejecutable)
    print("Entorno virtual  :", "[OK] Activo" if en_venv else "[AVISO] Python del sistema")
    print("Directorio actual:", Path.cwd())
    print("Sistema Operativo:", platform.system(), platform.release())
    print("Versión Python   :", sys.version.split()[0])
    print("\nVerificación de Librerías:")
    
    versiones = {}
    for nombre in dependencias:
        try:
            modulo = importlib.import_module(nombre)
            version = getattr(modulo, "__version__", "sin versión")
            versiones[nombre] = version
            print(f"  [OK] {nombre:12} {version}")
        except ImportError:
            versiones[nombre] = None
            print(f"  [FALTA] {nombre:12} Instalar con pip install {nombre}")
            
    reporte["versiones"] = versiones
    return reporte

ENTORNO = verificar_entorno(DEPENDENCIAS)

Intérprete       : c:\Users\jorge\f1_s01_evaluacion_entregable_grupo7\.venv\Scripts\python.exe
Entorno virtual  : [OK] Activo
Directorio actual: c:\Users\jorge\f1_s01_evaluacion_entregable_grupo7\F1
Sistema Operativo: Windows 11
Versión Python   : 3.14.7

Verificación de Librerías:
  [OK] numpy        2.5.2
  [OK] pandas       3.0.5
  [OK] matplotlib   3.11.1
  [OK] seaborn      0.13.2

## 3. Estructura del repositorio y dependencias

En esta sección se define y verifica la estructura de carpetas necesaria para organizar correctamente los archivos del proyecto.

Se comprueba la existencia de directorios destinados a:

- Datos originales.
- Datos procesados.
- Documentación.
- Código reutilizable.
- Las distintas fases del proyecto.

Además, se revisan archivos importantes para la reproducibilidad, como `.gitignore` y `requirements.txt`.

Esta organización permite mantener el proyecto ordenado y facilita que pueda ser ejecutado y revisado por otros integrantes del grupo.

In [6]:
from pathlib import Path

# 1. Detección automática de la raíz del proyecto (evita duplicar carpetas si estás dentro de F1/)
if Path.cwd().name == "F1":
    RAIZ = Path("..")
else:
    RAIZ = Path(".")

# 2. Definición de la estructura de carpetas institucionales
DIR_RAW = RAIZ / "data" / "raw"
DIR_PROCESSED = RAIZ / "data" / "processed"
DIR_DOCS = RAIZ / "docs"
DIR_SRC = RAIZ / "src"
DIR_FASES = [RAIZ / f"F{n}" for n in (1, 2, 3, 4)]

print("=== 1. VERIFICACIÓN Y CREACIÓN DE ESTRUCTURA ===")
for carpeta in [DIR_RAW, DIR_PROCESSED, DIR_DOCS, DIR_SRC, *DIR_FASES]:
    if not carpeta.exists():
        carpeta.mkdir(parents=True, exist_ok=True)
        print(f"  [CREADA] {carpeta.as_posix()}/")
    else:
        print(f"  [OK] Ya existe: {carpeta.as_posix()}/")

# 3. Escritura condicional de .gitignore (incluye data/raw/ para subir simce4b2025_rbd_final.csv)
print("\n=== 2. CONFIGURACIÓN DE GITIGNORE ===")
ARCHIVO_GITIGNORE = RAIZ / ".gitignore"
if not ARCHIVO_GITIGNORE.exists():
    GITIGNORE_CONTENT = """# Entorno virtual: se reconstruye con requirements.txt
.venv/

# Caché de Python
__pycache__/
*.pyc

# Jupyter
.ipynb_checkpoints/

# Archivos de sistema
Thumbs.db
desktop.ini
.DS_Store

# Variables de entorno y secretos
.env

# Modelos pesados y checkpoints
*.ckpt
*.pth
"""
    ARCHIVO_GITIGNORE.write_text(GITIGNORE_CONTENT, encoding="utf-8")
    print("✓ Archivo .gitignore generado por primera vez.")
else:
    print("✓ Archivo .gitignore ya existe (conservado sin modificar).")

# 4. Gestión de Dependencias (REQ_LINES)
print("\n=== 3. ARTEFACTO DE REQUIREMENTS ===")

# SIEMPRE se define REQ_LINES en la memoria del Notebook para que el README la use
if 'ENTORNO' in locals() and "versiones" in ENTORNO:
    REQ_LINES = [f"{pkg}=={ver}" for pkg, ver in ENTORNO["versiones"].items() if ver]
else:
    REQ_LINES = ["pandas", "numpy", "matplotlib", "seaborn"]

REQ_LINES += ["jupyterlab", "notebook", "ipykernel"]
REQ_LINES = sorted(list(set(REQ_LINES)))

# Solo se escribe el archivo físico si no existía previamente
ARCHIVO_REQUIREMENTS = RAIZ / "requirements.txt"
if not ARCHIVO_REQUIREMENTS.exists():
    ARCHIVO_REQUIREMENTS.write_text("\n".join(REQ_LINES) + "\n", encoding="utf-8")
    print("✓ Archivo requirements.txt generado por primera vez en el disco.")
else:
    print("✓ Archivo requirements.txt ya existe en el disco (variable REQ_LINES asegurada en memoria).")

=== 1. VERIFICACIÓN Y CREACIÓN DE ESTRUCTURA ===
  [OK] Ya existe: ../data/raw/
  [OK] Ya existe: ../data/processed/
  [OK] Ya existe: ../docs/
  [OK] Ya existe: ../src/
  [OK] Ya existe: ../F1/
  [OK] Ya existe: ../F2/
  [OK] Ya existe: ../F3/
  [OK] Ya existe: ../F4/

=== 2. CONFIGURACIÓN DE GITIGNORE ===
✓ Archivo .gitignore ya existe (conservado sin modificar).

=== 3. ARTEFACTO DE REQUIREMENTS ===
✓ Archivo requirements.txt ya existe en el disco (variable REQ_LINES asegurada en memoria).

## 4. Ficha y evaluación del dataset

En esta sección se documentan las principales características del conjunto de datos seleccionado para el proyecto.

La ficha registra información como:

- El nombre y la fuente del dataset.
- La institución responsable de los datos.
- La unidad de observación.
- El número de filas y columnas.
- Los distintos tipos y roles de las variables.
- La presencia de valores faltantes.

Además, se evalúa si el conjunto de datos cumple con los requisitos necesarios para continuar con las siguientes fases del proyecto.

Esta documentación permite conocer y justificar el dataset antes de realizar procesos de limpieza, transformación o análisis.

In [7]:
FICHA = {
    "titulo": "Resultados prueba SIMCE 4º Básico 2025 por Establecimiento",
    "autor": "Agencia de Calidad de la Educación",
    "plataforma": "Bases de datos públicas de la Agencia de Calidad de la Educación",
    "url": "https://informacionestadistica.agenciaeducacion.cl/#/bases",
    "licencia_abierta": None,  # Pendiente confirmar las condiciones de uso.
    "unidad_observacion": "Un establecimiento educacional (RBD)",
    "filas": 7143,
    "columnas": 42,
    "tamano_mb": 1.28,
    "roles": {},  # Se calculan desde el diccionario.
    "pct_nulos_max_variable": None,
    "pct_nulos_min_no_cero": None
}

CRITERIOS = {
    "filas": ("Filas mínima", 2000),
    "columnas": ("Columnas mínima", 12),
    "continua": ("Variables numéricas continuas", 2),
    "nominal": ("Variables categóricas nominales", 2),
    "ordinal": ("Variables ordinales/binarias", 1)
}

def evaluar_criterios(ficha):
    filas_eval = []
    roles = ficha["roles"]
    
    filas_eval.append({"criterio": "Mínimo de filas", "exigido": 2000, "observado": ficha["filas"], "cumple": "sí" if ficha["filas"]>=2000 else "NO"})
    filas_eval.append({"criterio": "Mínimo de columnas", "exigido": 12, "observado": ficha["columnas"], "cumple": "sí" if ficha["columnas"]>=12 else "NO"})
    filas_eval.append({"criterio": "Variables continuas", "exigido": 2, "observado": roles["continua"], "cumple": "sí" if roles["continua"]>=2 else "NO"})
    filas_eval.append({"criterio": "Presencia de nulos para preprocesar (≥1%)", "exigido": 1.0, "observado": ficha["pct_nulos_max_variable"], "cumple": "sí" if ficha["pct_nulos_max_variable"]>=1.0 else "NO"})
    
    df_eval = pd.DataFrame(filas_eval)
    return df_eval

# Evaluamos después de leer el CSV, usando sus valores reales.

## 5. Diccionario de variables y disponibilidad del dataset

En esta sección se documentan las variables que componen el conjunto de datos utilizado en el proyecto y se verifica la disponibilidad física del archivo original.

Para cada variable se registra:

- Su nombre.
- Su rol analítico.
- Una breve descripción de su significado.

Posteriormente, se comprueba que el archivo original exista en la carpeta `data/raw/` y que sus dimensiones coincidan con las declaradas en la ficha del dataset.

En esta fase los datos solo se inspeccionan y documentan; no se realizan procesos de limpieza, transformación ni análisis.

In [8]:
DICCIONARIO_DATA = [
    ("rbd", "identificador", "Rol Base de Datos del colegio"),
    ("dvrbd", "identificador", "Dígito verificador del RBD"),
    ("nom_rbd", "alta_cardinalidad", "Nombre oficial del establecimiento"),
    ("cod_reg_rbd", "nominal", "Código numérico de la región"),
    ("nom_reg_rbd", "nominal", "Nombre de la región geográfica"),
    ("cod_pro_rbd", "nominal", "Código numérico de la provincia"),
    ("nom_pro_rbd", "nominal", "Nombre de la provincia"),
    ("cod_com_rbd", "nominal", "Código de la comuna"),
    ("nom_com_rbd", "nominal", "Nombre de la comuna"),
    ("cod_deprov_rbd", "nominal", "Código departamento provincial"),
    ("nom_deprov_rbd", "nominal", "Nombre departamento provincial"),
    ("cod_depe1", "nominal", "Dependencia administrativa estructurada"),
    ("cod_depe2", "nominal", "Dependencia agregada (Municipal, Subvencionado, Pagado, SLEP)"),
    ("cod_grupo", "ordinal", "Grupo socioeconómico del colegio (1:Bajo a 5:Alto)"),
    ("cod_rural_rbd", "nominal", "Categoría de ruralidad (1:Urbano, 2:Rural)"),
    ("nalu_lect4b_rbd", "discreta", "Número de alumnos evaluados en Lectura"),
    ("nalu_mate4b_rbd", "discreta", "Número de alumnos evaluados en Matemática"),
    ("prom_lect4b_rbd", "continua", "Puntaje promedio SIMCE Lectura 4º Básico"),
    ("prom_mate4b_rbd", "continua", "Puntaje promedio SIMCE Matemática 4º Básico"),
    ("dif_lect4b_rbd", "continua", "Diferencia de puntaje Lectura respecto al año anterior"),
    ("dif_mate4b_rbd", "continua", "Diferencia de puntaje Matemática respecto al año anterior"),
    ("difgru_lect4b_rbd", "continua", "Diferencia de Lectura respecto a su grupo socioeconómico"),
    ("difgru_mate4b_rbd", "continua", "Diferencia de Matemática respecto a su grupo socioeconómico"),
    ("sigdif_lect4b_rbd", "nominal", "Significancia estadística de la diferencia en Lectura"),
    ("sigdif_mate4b_rbd", "nominal", "Significancia estadística de la diferencia en Matemática"),
    ("siggru_lect4b_rbd", "nominal", "Significancia de la diferencia respecto al grupo socioeconómico en Lectura"),
    ("siggru_mate4b_rbd", "nominal", "Significancia de la diferencia respecto al grupo socioeconómico en Matemática"),
    ("marca_lect4b_rbd", "nominal", "Marca de resguardo de calidad en Lectura"),
    ("marca_mate4b_rbd", "nominal", "Marca de resguardo de calidad en Matemática"),
    ("marcadif_lect4b_rbd", "nominal", "Marca de comparación histórica en Lectura"),
    ("marcadif_mate4b_rbd", "nominal", "Marca de comparación histórica en Matemática"),
    ("palu_eda_ins_lect4b_rbd", "continua", "Porcentaje de alumnos en Nivel Insuficiente (Lectura)"),
    ("palu_eda_ele_lect4b_rbd", "continua", "Porcentaje de alumnos en Nivel Elemental (Lectura)"),
    ("palu_eda_ade_lect4b_rbd", "continua", "Porcentaje de alumnos en Nivel Adecuado (Lectura)"),
    ("palu_eda_ins_mate4b_rbd", "continua", "Porcentaje de alumnos en Nivel Insuficiente (Matemática)"),
    ("palu_eda_ele_mate4b_rbd", "continua", "Porcentaje de alumnos en Nivel Elemental (Matemática)"),
    ("palu_eda_ade_mate4b_rbd", "continua", "Porcentaje de alumnos en Nivel Adecuado (Matemática)"),
    ("noaplica", "nominal", "Indicador de no aplicación del instrumento"),
    ("codigo_bbdd", "nominal", "Código de versión de la base de datos"),
    ("fecha_bbdd", "fecha", "Fecha de publicación de la base de datos"),
    ("grado", "nominal", "Grado evaluado (4b)"),
    ("agno", "discreta", "Año del proceso de evaluación (2025)")
]

diccionario = pd.DataFrame(DICCIONARIO_DATA, columns=["variable", "rol_analitico", "descripcion"])
assert len(diccionario) == FICHA["columnas"], "El diccionario debe cubrir las 42 variables exactas."
print(f"✓ Diccionario completo creado exitosamente ({len(diccionario)} variables).")
display(diccionario.head(10))

✓ Diccionario completo creado exitosamente (42 variables).

         variable      rol_analitico                         descripcion
0             rbd      identificador       Rol Base de Datos del colegio
1           dvrbd      identificador          Dígito verificador del RBD
2         nom_rbd  alta_cardinalidad  Nombre oficial del establecimiento
3     cod_reg_rbd            nominal        Código numérico de la región
4     nom_reg_rbd            nominal      Nombre de la región geográfica
5     cod_pro_rbd            nominal     Código numérico de la provincia
6     nom_pro_rbd            nominal              Nombre de la provincia
7     cod_com_rbd            nominal                 Código de la comuna
8     nom_com_rbd            nominal                 Nombre de la comuna
9  cod_deprov_rbd            nominal      Código departamento provincial

In [9]:
ARCHIVO_RAW = DIR_RAW / "simce4b2025_rbd_final.csv"
df_verif = pd.read_csv(ARCHIVO_RAW, sep=";", encoding="cp1252")
assert set(df_verif.columns) == set(diccionario["variable"]), "Revisar cobertura del diccionario."
# Calculamos la ficha para evitar cifras desactualizadas al reemplazar el archivo.
nulos = df_verif.isna().mean().mul(100)
FICHA.update({
    "filas": len(df_verif), "columnas": len(df_verif.columns),
    "tamano_mb": round(ARCHIVO_RAW.stat().st_size / 1024**2, 2),
    "roles": diccionario["rol_analitico"].value_counts().to_dict(),
    "pct_nulos_max_variable": float(nulos.max()),
    "pct_nulos_min_no_cero": float(nulos[nulos.gt(0)].min()),
})
evaluacion_df = evaluar_criterios(FICHA)
display(evaluacion_df)
display(nulos.sort_values(ascending=False).head().rename("porcentaje_ausente").to_frame())
print("Dimensiones del bruto:", df_verif.shape)

                                    criterio  exigido    observado cumple
0                            Mínimo de filas   2000.0  7143.000000     sí
1                         Mínimo de columnas     12.0    42.000000     sí
2                        Variables continuas      2.0    12.000000     sí
3  Presencia de nulos para preprocesar (≥1%)      1.0    92.930141     sí

                         porcentaje_ausente
marca_mate4b_rbd                  92.930141
marca_lect4b_rbd                  92.594148
marcadif_mate4b_rbd               76.522470
marcadif_lect4b_rbd               76.172477
palu_eda_ade_lect4b_rbd           28.419432

Dimensiones del bruto: (7143, 42)

## 6. Control de versiones con Git

En esta sección se verifica que Git se encuentre disponible en el entorno de trabajo y se revisa el historial reciente de cambios realizados en el repositorio.

El control de versiones permite:

- Registrar las modificaciones realizadas en el proyecto.
- Identificar qué integrante realizó cada cambio.
- Mantener un historial de commits.
- Facilitar el trabajo colaborativo mediante GitHub.
- Recuperar versiones anteriores en caso de errores.

Esta verificación permite mantener trazabilidad sobre el desarrollo del proyecto y comprobar que el repositorio está siendo utilizado correctamente por el grupo.

In [10]:
def git(*args):
    """Ejecuta un comando de git en el sistema."""
    if shutil.which("git") is None:
        return False, "Git no está instalado."
    res = subprocess.run(["git", *args], capture_output=True, text=True)
    return res.returncode == 0, res.stdout.strip()

ok_git, v_git = git("--version")
print("Diagnóstico Git:", v_git if ok_git else "No detectado")

ok_log, log_git = git("log", "--oneline", "-5")
print("\nÚltimos Commits:")
print(log_git if ok_log and log_git else "Sin commits aún en esta rama.")

Diagnóstico Git: git version 2.55.0.windows.5

Últimos Commits:
2f7e7bf F2 Final y limpieza
9ec5314 Ajustes en la Estrategia de limpieza y tratamiento de nulos
320a751 Ajustes en la Estrategia de limpieza y tratamiento de nulos
7ef6bd3 docs: actualizar README
71c877e docs: actualizar README

## 7. Validación técnica de la fase

Esta sección verifica automáticamente que los principales componentes
construidos durante la Fase 1 existan y sean coherentes entre sí.

Se comprueba:

1. La estructura de carpetas del proyecto.
2. La existencia de `.gitignore` y `requirements.txt`.
3. La integridad de la ficha del conjunto SIMCE.
4. La coherencia entre la ficha y el diccionario de variables.
5. La existencia y dimensiones del dataset.
6. La disponibilidad de Git.

In [11]:
def validar_fase1():
    """
    Comprueba los principales elementos técnicos construidos
    durante la Fase 1.
    """

    print("VALIDACIÓN TÉCNICA DE LA FASE 1")
    print("-" * 50)

    # 1. Estructura de carpetas
    carpetas_esperadas = [
        DIR_RAW,
        DIR_PROCESSED,
        DIR_DOCS,
        DIR_SRC,
        *DIR_FASES
    ]

    faltantes = [
        str(carpeta)
        for carpeta in carpetas_esperadas
        if not carpeta.is_dir()
    ]

    assert not faltantes, f"Faltan carpetas: {faltantes}"

    print(
        f"[OK] Estructura completa "
        f"({len(carpetas_esperadas)} carpetas)"
    )


    # 2. Archivos del entorno reproducible
    for nombre in [".gitignore", "requirements.txt"]:

        archivo = RAIZ / nombre

        assert archivo.exists(), \
            f"Falta el archivo {nombre}"

        assert archivo.stat().st_size > 0, \
            f"El archivo {nombre} está vacío"

        print(
            f"[OK] {nombre} presente "
            f"({archivo.stat().st_size} bytes)"
        )


    # 3. Ficha del dataset
    claves_obligatorias = [
        "titulo",
        "autor",
        "url",
        "unidad_observacion",
        "filas",
        "columnas",
        "roles"
    ]

    for clave in claves_obligatorias:
        assert clave in FICHA, \
            f"Falta '{clave}' en la ficha del dataset"

    print("[OK] Ficha del dataset completa")


    # 4. Coherencia entre ficha y diccionario
    assert len(diccionario) == FICHA["columnas"], \
        "El número de variables del diccionario no coincide con la ficha"

    assert diccionario["rol_analitico"].notna().all(), \
        "Existen variables sin rol analítico"

    roles = diccionario["rol_analitico"].nunique()

    print(
        f"[OK] Diccionario coherente: "
        f"{len(diccionario)} variables y {roles} roles"
    )


    # 5. Dataset
    if ARCHIVO_RAW.exists():

        df_validacion = pd.read_csv(
            ARCHIVO_RAW,
            sep=";",
            encoding="latin-1"
        )

        assert df_validacion.shape == (
            FICHA["filas"],
            FICHA["columnas"]
        ), "Las dimensiones del dataset no coinciden con la ficha"

        print(
            f"[OK] Dataset localizado: "
            f"{df_validacion.shape[0]:,} filas x "
            f"{df_validacion.shape[1]} columnas"
        )

    else:
        print(
            f"[PENDIENTE] El dataset no está disponible en "
            f"{ARCHIVO_RAW.as_posix()}"
        )


    # 6. Git
    ok_git, version_git = git("--version")

    assert ok_git, \
        "Git no está disponible en el entorno"

    print(f"[OK] Git disponible: {version_git}")


    print("\n✓ VALIDACIÓN TÉCNICA DE F1 COMPLETADA")

    return True

In [12]:
validar_fase1()

VALIDACIÓN TÉCNICA DE LA FASE 1
--------------------------------------------------
[OK] Estructura completa (8 carpetas)
[OK] .gitignore presente (146 bytes)
[OK] requirements.txt presente (120 bytes)
[OK] Ficha del dataset completa
[OK] Diccionario coherente: 42 variables y 7 roles
[OK] Dataset localizado: 7,143 filas x 42 columnas
[OK] Git disponible: git version 2.55.0.windows.5

✓ VALIDACIÓN TÉCNICA DE F1 COMPLETADA

True

## 8. Vinculación con el mapa conceptual

Esta sección relaciona los elementos definidos en la planificación conceptual con su
implementación real dentro del proyecto.

Para cada elemento se identifica:

1. El nodo o concepto del mapa conceptual.
2. La fase en que se implementa.
3. Su estado actual: **Implementado** o **Proyectado**.
4. La evidencia verificable dentro de F1, F2, `data/processed/`, `docs/` o el repositorio.

La vinculación distingue explícitamente lo ya construido en F1–F2 de los análisis
descriptivos, inferenciales y de visualización que corresponden a fases posteriores.

In [13]:
VINCULACION = [
    (
        "Problemática y objetivos",
        "F1",
        "Implementado",
        (
            "PROYECTO contiene la problemática, preguntas de investigación, "
            "objetivo general, objetivos específicos, alcance, restricciones "
            "y supuestos del proyecto."
        ),
    ),

    (
        "Entorno reproducible",
        "F1",
        "Implementado",
        (
            "verificar_entorno(), requirements.txt y la configuración del kernel "
            "documentan el entorno técnico necesario para reproducir el proyecto."
        ),
    ),

    (
        "Fuente y calidad del dato",
        "F1",
        "Implementado",
        (
            "FICHA, el diccionario de 42 variables y la evaluación de criterios "
            "documentan la estructura completa del archivo SIMCE original."
        ),
    ),

    (
        "Estructura y control de versiones",
        "F1",
        "Implementado",
        (
            "La estructura F1-F4, data, docs y src, junto con el diagnóstico de Git "
            "y el historial de commits, dejan evidencia de organización y trazabilidad."
        ),
    ),

    (
        "Carga selectiva del dataset",
        "F2",
        "Implementado",
        (
            "El F2 final carga 20 variables necesarias desde los 7.143 registros "
            "del dataset bruto, preservando sin modificaciones el archivo de data/raw/."
        ),
    ),

    (
        "Exploración y calidad inicial",
        "F2",
        "Implementado",
        (
            "F2 diagnostica dimensiones, tipos de datos, valores ausentes, duplicados "
            "y características del dataset antes de aplicar transformaciones."
        ),
    ),

    (
        "Tratamiento de valores ausentes",
        "F2",
        "Implementado",
        (
            "No se imputan RBD, información territorial ni puntajes SIMCE. "
            "Las variables porcentuales de estándares de aprendizaje fueron "
            "excluidas del alcance del producto analítico de F2."
        ),
    ),

    (
        "Transformación y enriquecimiento",
        "F2",
        "Implementado",
        (
            "F2 aplica conversión controlada de tipos, procesamiento de fecha_bbdd, "
            "limpieza de textos, traducción de códigos categóricos y enriquecimiento "
            "mediante DimGeografia."
        ),
    ),

    (
        "Control de representatividad",
        "F2",
        "Implementado",
        (
            "La regla de efectividad clasifica cada establecimiento como Efectivo o "
            "No Efectivo considerando alumnos evaluados y observaciones al puntaje."
        ),
    ),

    (
        "Auditoría de exclusiones",
        "F2",
        "Implementado",
        (
            "data/processed/auditoria_filtro.csv conserva los 619 registros No Efectivos "
            "junto con su motivo de exclusión y el indicador marca_2_con_puntaje; "
            "55 exclusiones conservan puntaje."
        ),
    ),

    (
        "Cobertura territorial",
        "F2",
        "Implementado",
        (
            "data/processed/cobertura_regional.csv registra por región los registros "
            "originales, efectivos, no efectivos, excluidos con puntaje y cantidades "
            "de alumnos antes y después del filtro."
        ),
    ),

    (
        "Dataset analítico final",
        "F2",
        "Implementado",
        (
            "El F2 final genera 6.524 establecimientos Efectivos y 30 variables, "
            "con una fila por RBD y la información necesaria para el análisis "
            "territorial posterior."
        ),
    ),

    (
        "Validación técnica",
        "F1-F2",
        "Implementado",
        (
            "validar_fase1() y las validaciones del F2 comprueban integridad, "
            "reconciliación y casos normales, límite y excepción."
        ),
    ),

    (
        "Análisis descriptivo territorial",
        "Fase posterior",
        "Proyectado",
        (
            "Comparación de puntajes promedio por región, provincia y comuna "
            "utilizando exclusivamente el dataset validado de F2."
        ),
    ),

    (
        "Análisis inferencial",
        "Fase posterior",
        "Proyectado",
        (
            "Aplicación de técnicas estadísticas para determinar si las diferencias "
            "territoriales observadas son estadísticamente significativas."
        ),
    ),

    (
        "Identificación de focos de menor desempeño",
        "Fase posterior",
        "Proyectado",
        (
            "Identificación de establecimientos y territorios con resultados inferiores "
            "a los niveles de referencia definidos durante el análisis."
        ),
    ),

    (
        "Visualización y comunicación",
        "Fase posterior",
        "Proyectado",
        (
            "Construcción de gráficos, tablas e informe técnico para comunicar "
            "resultados, limitaciones y conclusiones."
        ),
    ),
]


vinculacion = pd.DataFrame(
    VINCULACION,
    columns=[
        "nodo_mapa",
        "fase",
        "estado",
        "evidencia",
    ],
)


assert vinculacion["evidencia"].str.strip().ne("").all(), (
    "Hay elementos del mapa conceptual sin evidencia o proyección."
)

assert vinculacion["estado"].isin(
    [
        "Implementado",
        "Proyectado",
    ]
).all(), (
    "Existe un estado de vinculación no reconocido."
)


print(
    f"{len(vinculacion)} elementos vinculados: "
    f"{(vinculacion['estado'] == 'Implementado').sum()} implementados y "
    f"{(vinculacion['estado'] == 'Proyectado').sum()} proyectados."
)

display(vinculacion)

17 elementos vinculados: 13 implementados y 4 proyectados.

,nodo_mapa,fase,estado,evidencia
0,Problemática y objetivos,F1,Implementado,"PROYECTO contiene la problemática, preguntas d..."
1,Entorno reproducible,F1,Implementado,"verificar_entorno(), requirements.txt y la con..."
2,Fuente y calidad del dato,F1,Implementado,"FICHA, el diccionario de 42 variables y la eva..."
3,Estructura y control de versiones,F1,Implementado,"La estructura F1-F4, data, docs y src, junto c..."
4,Carga selectiva del dataset,F2,Implementado,El F2 final carga 20 variables necesarias desd...
5,Exploración y calidad inicial,F2,Implementado,"F2 diagnostica dimensiones, tipos de datos, va..."
6,Tratamiento de valores ausentes,F2,Implementado,"No se imputan RBD, información territorial ni ..."
7,Transformación y enriquecimiento,F2,Implementado,"F2 aplica conversión controlada de tipos, proc..."
8,Control de representatividad,F2,Implementado,La regla de efectividad clasifica cada estable...
9,Auditoría de exclusiones,F2,Implementado,data/processed/auditoria_filtro.csv conserva l...
10,Cobertura territorial,F2,Implementado,data/processed/cobertura_regional.csv registra...
11,Dataset analítico final,F2,Implementado,El F2 final genera 6.524 establecimientos Efec...
12,Validación técnica,F1-F2,Implementado,validar_fase1() y las validaciones del F2 comp...
13,Análisis descriptivo territorial,Fase posterior,Proyectado,"Comparación de puntajes promedio por región, p..."
14,Análisis inferencial,Fase posterior,Proyectado,Aplicación de técnicas estadísticas para deter...
15,Identificación de focos de menor desempeño,Fase posterior,Proyectado,Identificación de establecimientos y territori...
16,Visualización y comunicación,Fase posterior,Proyectado,"Construcción de gráficos, tablas e informe téc..."

> **Vinculación con el informe.**
> Cada elemento del mapa conceptual debe relacionarse con evidencia concreta dentro
> del proyecto: una celda de F1 o F2, un archivo del repositorio, un producto en
> `data/processed/`, documentación en `docs/` o un registro de Git.
>
> Los componentes aún no ejecutados se identifican explícitamente como **Proyectados**
> para mantener coherencia entre la planificación conceptual y el avance técnico real.

## 9. Persistencia y trazabilidad

El resultado de la Fase 1 debe quedar guardado y documentado de forma
reproducible.

En esta sección se generan y almacenan los principales artefactos de la fase:

- `README.md` del proyecto.
- Diccionario de variables.
- Evaluación de los criterios del dataset.
- Vinculación con el mapa conceptual.
- Metadatos de ejecución de la Fase 1.

Estos archivos permiten mantener trazabilidad entre el notebook, el repositorio
GitHub y el informe técnico.

In [14]:
import sys
from pathlib import Path

# 1. Definición de variables de proyecto
TITULO_PROYECTO = "Caracterización e Inequidad en los Resultados Académicos del SIMCE 4º Básico en Chile"
GRUPO = "Grupo 7"
INTEGRANTES = ["Felipe Palma Barrientos", "Vicente Aguilar Rojas", "Cristian Grandon Grandon", "Jorge Gutierrez Jaramillo"]
SEMILLA = 42

# 2. Resguardo por si FICHA o REQ_LINES no se ejecutaron previamente
if 'FICHA' not in locals():
    FICHA = {
        'titulo': 'Resultados SIMCE 4º Básico 2025',
        'autor': 'Agencia de Calidad de la Educación',
        'plataforma': 'Bases de datos públicas de la Agencia de Calidad de la Educación',
        'url': 'https://informacionestadistica.agenciaeducacion.cl/#/bases',
        'unidad_observacion': 'Un establecimiento educacional (RBD)',
        'filas': 7143,
        'columnas': 42
    }

if 'REQ_LINES' not in locals():
    REQ_LINES = ["pandas", "numpy", "matplotlib", "seaborn", "jupyterlab"]

# 3. Definición de la función generar_readme
def generar_readme(titulo, grupo, integrantes, ficha, dependencias, ruta):
    """Genera el README técnico del proyecto."""

    lista_integrantes = "\n".join(
        f"- {nombre}" for nombre in integrantes
    )

    lista_dependencias = "\n".join(
        f"- {dep}" for dep in dependencias
    )

    contenido = f"""# {titulo}

**Grupo:** {grupo}

## Integrantes
{lista_integrantes}

## Datos
- Dataset: {ficha['titulo']}
- Fuente: {ficha['autor']}
- Plataforma: {ficha['plataforma']}
- Enlace: {ficha['url']}
- Unidad de observación: {ficha['unidad_observacion']}
- Dimensiones: {ficha['filas']:,} filas x {ficha['columnas']} columnas

## Estructura del repositorio

- `data/raw/`: datos originales sin modificar.
- `data/processed/`: datos procesados en fases posteriores.
- `docs/`: documentación y metadatos.
- `src/`: módulos reutilizables.
- `F1/`: definición y preparación del proyecto.
- `F2/`: procesamiento de datos.
- `F3/` y `F4/`: fases posteriores.

## Requisitos

Python: {sys.version.split()[0]}

### Dependencias
{lista_dependencias}

## Reproducibilidad

La semilla utilizada durante el proyecto es `{SEMILLA}`.

Los datos originales no se modifican durante la Fase 1.
"""

    # Conservamos los acuerdos y notas que el grupo agregó al README.
    if ruta.exists():
        return ruta.read_text(encoding="utf-8")
    ruta.write_text(contenido, encoding="utf-8")

    return contenido

# 4. Asegurar ruta raíz correcta (independiente de si ejecutas desde F1/ o la raíz)
RAIZ = Path("..") if Path.cwd().name == "F1" else Path(".")
ARCHIVO_README = RAIZ / "README.md"

# 5. Ejecución con los 6 argumentos obligatorios
contenido_readme = generar_readme(
    TITULO_PROYECTO,
    GRUPO,
    INTEGRANTES,
    FICHA,
    REQ_LINES,
    ARCHIVO_README
)

print(
    f"✓ README disponible "
    f"({len(contenido_readme.splitlines())} líneas) en {ARCHIVO_README.resolve()}"
)

✓ README disponible (414 líneas) en C:\Users\jorge\f1_s01_evaluacion_entregable_grupo7\README.md

In [15]:
# Guardar diccionario de variables
diccionario.to_csv(
    DIR_DOCS / "diccionario_variables.csv",
    index=False
)

# Guardar evaluación del dataset
evaluacion_df.to_csv(
    DIR_DOCS / "evaluacion_criterios_dataset.csv",
    index=False
)

# Guardar vinculación con el mapa conceptual
vinculacion.to_csv(
    DIR_DOCS / "vinculacion_mapa_conceptual.csv",
    index=False
)


# Metadatos de ejecución de la Fase 1
METADATOS = {
    "proyecto": TITULO_PROYECTO,
    "grupo": GRUPO,
    "fase": "F1",
    "fecha_ejecucion": date.today().isoformat(),
    "semilla": SEMILLA,

    "python": sys.version.split()[0],

    "sistema_operativo": (
        f"{platform.system()} {platform.release()}"
    ),

    "interprete": ENTORNO["interprete"],

    "entorno_virtual": ENTORNO["entorno_virtual"],

    "dependencias": ENTORNO["versiones"],

    "dataset": {
        "titulo": FICHA["titulo"],
        "fuente": FICHA["autor"],
        "url": FICHA["url"],
        "filas": FICHA["filas"],
        "columnas": FICHA["columnas"],
        "archivo_disponible": ARCHIVO_RAW.exists(),
        "roles": FICHA["roles"],
        "pct_nulos_max_variable": FICHA["pct_nulos_max_variable"],
        "licencia_abierta": FICHA["licencia_abierta"]
    }
}


# Guardar los metadatos como JSON
archivo_metadatos = DIR_DOCS / "metadatos_fase1.json"

archivo_metadatos.write_text(
    json.dumps(
        METADATOS,
        indent=2,
        ensure_ascii=False
    ),
    encoding="utf-8"
)


print("✓ Artefactos de F1 guardados:\n")

for archivo in sorted(DIR_DOCS.iterdir()):
    print(
        f"  {archivo.name:40} "
        f"{archivo.stat().st_size:8} bytes"
    )

✓ Artefactos de F1 guardados:

  diccionario_variables.csv                    2962 bytes
  evaluacion_criterios_dataset.csv              211 bytes
  metadatos_fase1.json                         1095 bytes
  vinculacion_mapa_conceptual.csv              3371 bytes

In [16]:
criterios_incumplidos = (
    evaluacion_df["cumple"] == "NO"
).sum()


resumen_f1 = pd.DataFrame([
    {
        "artefacto": "Variables documentadas",
        "estado": len(diccionario)
    },
    {
        "artefacto": "Elementos del mapa vinculados",
        "estado": len(vinculacion)
    },
    {
        "artefacto": "Criterios de dataset incumplidos",
        "estado": criterios_incumplidos
    },
    {
        "artefacto": "Archivos generados en docs/",
        "estado": len(list(DIR_DOCS.iterdir()))
    },
    {
        "artefacto": "Dataset disponible",
        "estado": "Sí" if ARCHIVO_RAW.exists() else "No"
    },
    {
        "artefacto": "README generado",
        "estado": "Sí" if ARCHIVO_README.exists() else "No"
    }
])

display(resumen_f1)

                          artefacto estado
0            Variables documentadas     42
1     Elementos del mapa vinculados     17
2  Criterios de dataset incumplidos      0
3       Archivos generados en docs/      4
4                Dataset disponible     Sí
5                   README generado     Sí

## Conclusiones y trazabilidad

La Fase 1 deja operativo el entorno técnico y metodológico necesario para continuar el proyecto **Caracterización e Inequidad en los Resultados Académicos del SIMCE 4º Básico en Chile**. En esta etapa se definieron la problemática, las preguntas de investigación, los objetivos, el alcance, las restricciones y los supuestos que orientan el análisis posterior.

El conjunto de datos seleccionado corresponde a la base pública SIMCE 2025 por establecimiento educacional, utilizando como unidad de observación el RBD. El archivo original contiene **7.143 registros y 42 variables**, las cuales fueron documentadas mediante un diccionario que identifica su función dentro del proyecto. La evaluación técnica realizada en esta fase confirma que el conjunto satisface los criterios definidos para continuar con su procesamiento.

La reproducibilidad del proyecto queda respaldada mediante una estructura organizada de carpetas, uso de rutas relativas, semilla global, registro del entorno de ejecución y artefactos como `.gitignore`, `requirements.txt` y `README.md`. Además, se generan archivos de documentación persistente en `docs/`, incluyendo el diccionario de variables, la evaluación del dataset, la vinculación con el mapa conceptual y los metadatos de ejecución.

Las principales tareas de F1 fueron implementadas mediante funciones documentadas y verificables, entre ellas `presentar_proyecto()`, `verificar_entorno()`, `evaluar_criterios()`, `git()`, `validar_fase1()` y `generar_readme()`. Estas funciones permiten separar responsabilidades y mantener un flujo técnico comprensible y reproducible.

**Trazabilidad con el repositorio (F1):** este notebook se mantiene dentro de la carpeta `F1/`; el archivo `README.md` documenta la estructura, dependencias y forma de ejecución del proyecto; `docs/` conserva los productos documentales generados durante la fase; y Git/GitHub mantiene un historial verificable de los cambios y contribuciones realizadas por el equipo.

La vinculación con el mapa conceptual permite comprobar además la continuidad entre fases: F1 define y valida el proyecto y sus datos; F2 realiza la carga selectiva, limpieza, transformación, auditoría y construcción del dataset analítico; mientras que los análisis estadísticos, visualizaciones y demás componentes quedan proyectados para las fases posteriores.

## 10. Reflexión técnica

### Hallazgos

- **El conjunto SIMCE 2025 cumple los criterios definidos para el proyecto.** La evaluación realizada durante F1 confirmó que dispone de un volumen suficiente de registros y variables, distintos tipos y roles analíticos y la estructura necesaria para desarrollar las etapas posteriores de preprocesamiento y análisis.

- **La unidad de observación condiciona la interpretación de los resultados.** El proyecto trabaja a nivel de establecimiento educacional identificado mediante RBD y no a nivel individual de estudiante. Por lo tanto, las comparaciones posteriores describirán diferencias entre establecimientos y territorios y no relaciones causales sobre estudiantes individuales.

- **Documentar la base completa antes de seleccionar variables mejora la trazabilidad.** Aunque F2 utiliza solamente las variables necesarias para el pipeline analítico, F1 conserva la documentación de las 42 variables originales. Esto permite distinguir claramente entre la estructura del dato de origen y el subconjunto utilizado para el análisis.

- **La reproducibilidad debe quedar respaldada por evidencia técnica.** No basta con que el notebook funcione en el equipo donde fue creado. Por ello se verifican el intérprete, el entorno virtual, las versiones de las librerías, los archivos de dependencias, la estructura del repositorio y la disponibilidad de Git.

### Dificultades y cómo se resolvieron

- **Rutas y ubicación de ejecución.** Se utilizaron rutas relativas mediante `pathlib`, permitiendo que el proyecto identifique correctamente sus recursos tanto si el notebook se ejecuta desde la raíz del repositorio como desde la carpeta correspondiente a la fase.

- **Coherencia entre documentación y dataset real.** Se incorporaron validaciones que comprueban la existencia del archivo, sus dimensiones y la correspondencia entre la ficha técnica y el diccionario de variables. De esta forma se evita continuar el flujo con documentación desactualizada.

- **Separación de responsabilidades entre fases.** Se definió explícitamente que F1 se concentra en la definición del problema, la configuración del entorno, la documentación y la validación inicial, mientras que F2 se encarga del preprocesamiento efectivo de los datos.

- **Trazabilidad de las decisiones posteriores de filtrado.** La planificación del proyecto contempla que las exclusiones realizadas en F2 sean auditables y que su efecto territorial pueda ser analizado, evitando que el preprocesamiento elimine registros sin dejar evidencia.

### Decisiones que quedan abiertas

- Qué técnicas estadísticas se utilizarán para evaluar las diferencias observadas entre regiones, provincias y comunas.

- Qué criterios se utilizarán para identificar establecimientos o territorios con niveles de desempeño relativamente bajos.

- Qué visualizaciones permitirán comunicar de forma más clara las diferencias territoriales encontradas.

- Cómo se reorganizará el pipeline mediante **programación orientada a objetos en la Fase 3**, procurando mejorar encapsulamiento, mantenibilidad y reutilización sin alterar la lógica validada en F2.

## 11. Verificación antes de entregar

### Cuaderno

- El notebook ejecuta completamente mediante **Kernel → Restart Kernel and Run All Cells** sin errores.
- La secuencia de ejecución mantiene un flujo lógico y reproducible.
- Cada sección técnica está acompañada por explicación narrativa o comentarios pertinentes.
- Las rutas utilizadas son relativas.
- La semilla de reproducibilidad se encuentra declarada.

### Contenido técnico

- La problemática, las preguntas de investigación, los objetivos, el alcance, las restricciones y los supuestos están declarados.
- El entorno de ejecución se verifica mediante intérprete, entorno virtual y versiones de dependencias.
- La fuente y procedencia de la base SIMCE 2025 están documentadas.
- El dataset original se valida con **7.143 registros y 42 variables**.
- El diccionario documenta las **42 variables** y sus respectivos roles analíticos.
- El conjunto de datos fue evaluado contra los criterios técnicos definidos para el proyecto.
- La vinculación con el mapa conceptual distingue componentes implementados y proyectados.
- La validación técnica comprueba estructura del proyecto, archivos requeridos, dataset y disponibilidad de Git.

### Archivos

- `.gitignore` está disponible en la raíz y posee contenido.
- `requirements.txt` está disponible en la raíz y documenta las dependencias del proyecto.
- `README.md` documenta el proyecto, su estructura y reproducibilidad.
- `docs/diccionario_variables.csv` contiene el diccionario de las variables originales.
- `docs/evaluacion_criterios_dataset.csv` conserva el resultado de la evaluación del dataset.
- `docs/vinculacion_mapa_conceptual.csv` registra la correspondencia entre planificación e implementación.
- `docs/metadatos_fase1.json` conserva información reproducible de la ejecución.

### Repositorio

- La carpeta `F1/` contiene el notebook correspondiente a la definición inicial del proyecto.
- La estructura del repositorio contempla las carpetas requeridas para las fases del proyecto.
- El historial de Git/GitHub permite verificar la evolución del trabajo.
- Las contribuciones de los integrantes pueden identificarse mediante los commits del repositorio.
- El `README.md` se encuentra alineado con el estado actual de F1 y F2.